
# Generated by Django 3.1.7 on 2021-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['idx_id'], name='cars_car_idx_id_89e7aa_idx'),
        ),
        migrations.RunSQL(sql='''
            CREATE SEQUENCE IF NOT EXISTS idx_id_seq MINVALUE 1;

            CREATE OR REPLACE FUNCTION increase_idx_id()
            RETURNS trigger AS $increase_idx$
                BEGIN
                    NEW.idx_id := nextval('idx_id_seq');
                    RETURN NEW;
                END;
            $increase_idx$ LANGUAGE plpgsql;


            CREATE TRIGGER idx_id_car_increase
                BEFORE INSERT
                ON cars_car
                FOR EACH ROW
                EXECUTE PROCEDURE increase_idx_id();
        '''),
    ]
