# Generated by Django 3.1.7 on 2021-02-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-make']},
        ),
    ]
